### ISSUE TITLE
iPad Air get Error 

### ISSUE THREAD

**Issue by ghost** [maximbilan/UIAlertController-Customization#2]
Hello 
In iPad Air get Error, can you help me to solve it?

Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7ff57f833a00>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a source view and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

**Comment by maximbilan** [comment]
Hello,
I've just launched the example on the iPad. There is no issue.
![simulator screen shot - ipad 6th generation - 2018-09-18 at 14 04 00](https://user-images.githubusercontent.com/3020089/45683351-ff010b80-bb4b-11e8-99d9-c6a7c821a406.png)

**Comment by ghost** [comment]
no, I do it like your code but I get failed in iPad Air simulator

**Comment by maximbilan** [comment]
@omidshz100 So, is it an issue of your app? not about this example?
